language: node_js
node_js:
- '0.10'
env:
- NODE_ENV=travis
services:
- mongodb
deploy:
  app: siareport
  provider: heroku
  api_key:
    secure: YODC+Fl5JoEJ/Ih/8AhzK9D2J+z2uveok+SS+QDSrDBY6A+beo0k/WDSQXoYQIHwQ1ftMy23xMAs67a8eqAQjDyNCh6PwVzdSlx0bzM+W8ijyAuqrtwh/yFyhpdjVJbAc48Y4+tMJbZKJ1bujhQB1SpEDvY5FDVCIM+ZGEYrwGD8KxU+PHV5Mg/7r1bbcXbrqbySck/J9oEn58NNx6YFTnJm/uTu3lRfgwfJnliNhUaou6Sl8NSaA6u89xcLIPTAQwiduD9NuT3SKMW6cHTcR1WA8n8jjSHn28tqfRcTQ8ie34eTNHZnDzOLF0/Qxtn1LWgjdBQeib8s7TEl8H6S2MgBSX7QLPwFAdCXafdxaRVKS+LJLPbjn4eZyNiQLaEALkgaiHfNgyrVI7GZz6Hl4j+r2pP0XP2UPJo4W682mPtTVdYHUWibpeuaA1zKINmqxOf2FqUkAxfyqMqiTV1F/lBlexOnVtjwvTKoMlaq3HO2gz14DPJutGSlPbYSoxv5gPV4qlZNeeD6JQapGs1jAxZajKRGgatX1rc4VjvVue9RbMySfDO83gyqxpIpZC5U/FeGX5SsZWul4wgsa177aABOpxkX0eDFupz9JDEWRRFvhQh0mXV9SCEiSR16Vt+qGNtQBtObKpMyilN4I+qbwhZJfkE28CNRe0G2cxJ5Gl4=
